name: Auto-Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    name: Merge PR automatically
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'auto-merge') }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Merge pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" \
            --repo "${{ github.repository }}" \
            --squash
