name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Skip non-applicable workflow
      run: echo "Skipped: repository is not a Clojure project."
